# Generated by Django 5.1.5 on 2025-06-09 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('c_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=0)),
                ('c_color_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_v', to='products.colorvariant')),
                ('c_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.product')),
                ('c_size_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_v', to='products.sizevariant')),
                ('c_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
