# Generated by Django 5.1.5 on 2025-07-26 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_to_card', '0001_initial'),
        ('products', '0007_product_max_price_product_min_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='c_color_variant',
        ),
        migrations.RemoveField(
            model_name='card',
            name='c_size_variant',
        ),
        migrations.AddField(
            model_name='card',
            name='c_product_variant',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='card_product_variant', to='products.product_variant'),
        ),
    ]
