# Generated by Django 5.1.5 on 2025-07-26 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_to_card', '0002_remove_card_c_color_variant_and_more'),
        ('products', '0007_product_max_price_product_min_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='discount',
            fields=[
                ('d_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('discount_price', models.IntegerField(default=0)),
                ('discount_percentage', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='card',
            name='c_product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_product_variant', to='products.product_variant'),
        ),
    ]
