# Generated by Django 5.1.5 on 2025-07-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_to_card', '0003_discount_alter_card_c_product_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='coupon_discount',
            fields=[
                ('cd_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_percentage', models.IntegerField(default=0)),
                ('is_active_coupon', models.BooleanField(default=True)),
                ('usage_limit', models.IntegerField(default=1)),
            ],
        ),
        migrations.DeleteModel(
            name='discount',
        ),
    ]
