# Generated by Django 5.1.5 on 2025-07-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_to_card', '0004_coupon_discount_delete_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon_discount',
            name='max_numbers_of_products',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='coupon_discount',
            name='max_price',
            field=models.IntegerField(default=1),
        ),
    ]
