# Generated by Django 5.1.5 on 2025-07-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_to_card', '0005_coupon_discount_max_numbers_of_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_coupon_applied',
            field=models.BooleanField(default=0),
        ),
    ]
