# Generated by Django 5.1.4 on 2025-10-27 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_to_card', '0006_card_is_coupon_applied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='is_coupon_applied',
        ),
    ]
