# Generated by Django 5.1.4 on 2025-10-28 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=100)),
                ('admin_name', models.CharField(max_length=100)),
                ('admin_email', models.EmailField(max_length=100)),
                ('admin_dob', models.DateField(default=datetime.date(2000, 9, 27), verbose_name='Date of Birth')),
                ('code', models.IntegerField(default=0)),
            ],
        ),
    ]
