# Generated by Django 6.0 on 2025-12-13 07:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_p_gender'),
        ('review', '0002_order_comment_order_star_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='order',
            new_name='products_review',
        ),
    ]
