# Generated by Django 6.0 on 2025-12-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_rename_order_products_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='products_review',
            name='comment_or_not',
            field=models.BooleanField(default=0),
        ),
    ]
