# Generated by Django 5.1.5 on 2025-08-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='g_name',
            field=models.CharField(max_length=50),
        ),
    ]
