# Generated by Django 5.1.4 on 2025-11-07 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderhistory',
            name='date_shipped',
        ),
    ]
