# Generated by Django 5.1.4 on 2025-10-28 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='shipping_areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('base_charge', models.IntegerField(default=0)),
                ('additional_item_charge', models.IntegerField(default=0)),
                ('max_charges', models.IntegerField(default=0)),
                ('estimated_time', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('advance_payment_percent', models.IntegerField(default=0)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities_shipping_areas', to='shipping.cities')),
                ('country_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_areas_country', to='shipping.country')),
            ],
        ),
        migrations.CreateModel(
            name='customer_shipping_location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=30)),
                ('address1', models.CharField(max_length=200)),
                ('address2', models.CharField(max_length=200)),
                ('deleivery_charges', models.IntegerField(default=0)),
                ('product_price', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('advance_pay', models.IntegerField(default=0)),
                ('date_ordered', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_user_id', to=settings.AUTH_USER_MODEL)),
                ('shipping_area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_shipping_area', to='shipping.shipping_areas')),
            ],
        ),
    ]
