# Generated by Django 5.1.4 on 2025-10-29 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_shipping_location',
            name='delevery_option',
            field=models.CharField(default='now', max_length=20),
        ),
    ]
