# Generated by Django 5.1.4 on 2025-11-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_customer_shipping_location_delevery_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_shipping_location',
            name='online_paid',
            field=models.IntegerField(default=0),
        ),
    ]
