# Generated by Django 5.1.4 on 2025-11-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0003_customer_shipping_location_online_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_shipping_location',
            name='rest_for_delvery',
            field=models.IntegerField(default=0),
        ),
    ]
