# Generated by Django 5.1.4 on 2025-10-28 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shipping', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_address', models.CharField(max_length=200)),
                ('online_paid', models.IntegerField(default=0)),
                ('remaining_paid', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=0)),
                ('date_ordered', models.DateTimeField()),
                ('phone_number', models.CharField(max_length=30)),
                ('address1', models.CharField(max_length=200)),
                ('address2', models.CharField(max_length=200)),
                ('product_price', models.IntegerField(default=0)),
                ('notes', models.TextField()),
                ('shipping_area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_shipping_area', to='shipping.shipping_areas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
