# Generated by Django 5.1.4 on 2025-10-29 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delevery_option',
            field=models.CharField(default='now', max_length=20),
        ),
    ]
