# Generated by Django 5.1.4 on 2025-10-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address2',
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
