# Generated by Django 5.1.4 on 2025-11-05 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_order_address1_remove_order_address2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='admin_read_status',
        ),
        migrations.AddField(
            model_name='order',
            name='admin_stored_history',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='completes_tatus',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
