# Generated by Django 5.1.4 on 2025-11-05 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_rename_status_order_admin_read_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='completes_tatus',
            new_name='status',
        ),
    ]
