# Generated by Django 5.1.4 on 2025-11-05 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_rename_completes_tatus_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='completes_status',
        ),
    ]
