# Generated by Django 5.1.4 on 2025-11-05 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_rename_status_order_completes_status'),
        ('products', '0008_alter_product_p_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.CreateModel(
            name='orders_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=0)),
                ('c_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_product', to='products.product')),
                ('c_product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_product_variant', to='products.product_variant')),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_order', to='order.order')),
            ],
        ),
    ]
