# Generated by Django 5.1.4 on 2025-11-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_remove_order_products_orders_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_watched_success_page',
            field=models.BooleanField(default=0),
        ),
    ]
