# Generated by Django 5.1.4 on 2025-11-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_order_user_watched_success_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='DevelveryCode',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
