# Generated by Django 5.1.4 on 2025-11-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_order_develverycode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='DevelveryCode',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
