# Generated by Django 6.0 on 2025-12-12 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_alter_order_develverycode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='decrease_stack',
            field=models.IntegerField(default=0),
        ),
    ]
