# Generated by Django 5.1.5 on 2025-06-09 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=100)),
                ('color_code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SizeVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('p_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=100)),
                ('p_compony', models.CharField(max_length=100)),
                ('p_is_sale', models.BooleanField(default=False)),
                ('p_description', models.CharField(max_length=1500)),
                ('slug', models.SlugField()),
                ('p_child_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_child_category', to='categories.child_category')),
                ('p_gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_category', to='categories.gender')),
            ],
        ),
        migrations.CreateModel(
            name='product_image',
            fields=[
                ('i_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_image', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='product_variant',
            fields=[
                ('pv_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('price', models.IntegerField(default=0)),
                ('sale_price', models.IntegerField(default=0)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_product_variant', to='products.colorvariant')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_product_variant', to='products.sizevariant')),
            ],
        ),
    ]
