# Generated by Django 5.1.5 on 2025-07-11 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_variant_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_variant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_product_variant', to='products.product'),
        ),
    ]
