# Generated by Django 5.1.5 on 2025-07-13 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_variant_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_image',
            name='product_variant_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='product_variant', to='products.product_variant'),
            preserve_default=False,
        ),
    ]
