# Generated by Django 5.1.5 on 2025-07-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_image_product_variant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_variant',
            name='is_available',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='product_variant',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
