# Generated by Django 5.1.5 on 2025-07-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_variant_is_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='p_is_sale',
        ),
        migrations.AddField(
            model_name='product_variant',
            name='p_is_sale',
            field=models.BooleanField(default=False),
        ),
    ]
