# Generated by Django 5.1.5 on 2025-07-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_p_is_sale_product_variant_p_is_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='min_price',
            field=models.IntegerField(default=0),
        ),
    ]
