# Generated by Django 5.1.5 on 2025-08-27 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_gender_g_name'),
        ('products', '0007_product_max_price_product_min_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='p_gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_gender', to='categories.gender'),
        ),
    ]
