# Generated by Django 6.0 on 2025-12-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_p_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='average_star_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='rate_persons',
            field=models.IntegerField(default=0),
        ),
    ]
