# Generated by Django 6.0 on 2025-12-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_average_star_rate_product_rate_persons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='average_star_rate',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
